### ISSUE TITLE
sql server test bug

### ISSUE THREAD

**Issue by miguelgfierro** [miguelgfierro/codebase#272]
```
005 Create a table and drop it if it exists.
006     Args:
007         table_name (str): Table name.
008         cursor (object): pyobdc cursor.
009     Example:
010         >>> conn = pyodbc.connect(connection_string)
UNEXPECTED EXCEPTION: NameError("name 'connection_string' is not defined",)
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/doctest.py", line 1330, in __run
    compileflags, 1), test.globs)
  File "<doctest python.database.sql_server.create_table.create_table[0]>", line 1, in <module>
NameError: name 'connection_string' is not defined

```

**Comment by miguelgfierro** [comment]
also in 
```
/home/travis/build/miguelgfierro/codebase/python/database/sql_server/insert_values.py:14: UnexpectedException
/home/travis/build/miguelgfierro/codebase/python/database/sql_server/select_values.py:13: UnexpectedException
/home/travis/build/miguelgfierro/codebase/python/database/sql_server/select_values.py:35: UnexpectedException
```

**Comment by miguelgfierro** [comment]
error in path:

```

__________ [doctest] python.database.sqlite.insert_values.insert_csv ___________
035     Args:
036         cursor (object): sqlite cursor.
037         connector (object): sqlite connector.
038         table_name (str): Table name.
039         filename (str): Path to csv file.
040     Example:
041         >>> import os
042         >>> conn = sqlite3.connect('temp.db')
043         >>> instruction = '(t ,q0, q1) VALUES (?,?,?)'
044         >>> insert_csv(conn, 'table_csv', instruction, os.path.abspath('../../../share/traj.csv'))
UNEXPECTED EXCEPTION: FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/doctest.py", line 1330, in __run
    compileflags, 1), test.globs)
  File "<doctest python.database.sqlite.insert_values.insert_csv[3]>", line 1, in <module>
  File "/home/travis/build/miguelgfierro/codebase/python/database/sqlite/insert_values.py", line 52, in insert_csv
    f = open(filename,'r') # open the csv data file
FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/share/traj.csv'
/home/travis/build/miguelgfierro/codebase/python/database/sqlite/insert_values.py:44: UnexpectedException
```
